<?PHP
 if(!function_exists('ereg'))            { function ereg($pattern, $subject, &$matches = []) { return preg_match('/'.$pattern.'/', $subject, $matches); } }
if(!function_exists('eregi'))           { function eregi($pattern, $subject, &$matches = []) { return preg_match('/'.$pattern.'/i', $subject, $matches); } }
if(!function_exists('ereg_replace'))    { function ereg_replace($pattern, $replacement, $string) { return preg_replace('/'.$pattern.'/', $replacement, $string); } }
if(!function_exists('eregi_replace'))   { function eregi_replace($pattern, $replacement, $string) { return preg_replace('/'.$pattern.'/i', $replacement, $string); } }
if(!function_exists('split'))           { function split($pattern, $subject, $limit = -1) { return preg_split('/'.$pattern.'/', $subject, $limit); } }
if(!function_exists('spliti'))          { function spliti($pattern, $subject, $limit = -1) { return preg_split('/'.$pattern.'/i', $subject, $limit); } }

// images
$pngFolder = <<< EOFILE
iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAA3NCSVQICAjb4U/gAAABhlBMVEX//v7//v3///7//fr//fj+/v3//fb+/fT+/Pf//PX+/Pb+/PP+/PL+/PH+/PD+++/+++7++u/9+vL9+vH79+r79+n79uj89tj89Nf889D88sj78sz78sr58N3u7u7u7ev777j67bL67Kv46sHt6uP26cns6d356aP56aD56Jv45pT45pP45ZD45I324av344r344T14J734oT34YD13pD24Hv03af13pP233X025303JL23nX23nHz2pX23Gvn2a7122fz2I3122T12mLz14Xv1JPy1YD12Vz02Fvy1H7v04T011Py03j011b01k7v0n/x0nHz1Ejv0Hnuz3Xx0Gvz00buzofz00Pxz2juz3Hy0TrmznzmzoHy0Djqy2vtymnxzS3xzi/kyG3jyG7wyyXkwJjpwHLiw2Liw2HhwmDdvlXevVPduVThsX7btDrbsj/gq3DbsDzbrT7brDvaqzjapjrbpTraojnboTrbmzrbmjrbl0Tbljrakz3ajzzZjTfZijLZiTJdVmhqAAAAgnRSTlP///////////////////////////////////////8A////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////9XzUpQAAAAlwSFlzAAALEgAACxIB0t1+/AAAAB90RVh0U29mdHdhcmUATWFjcm9tZWRpYSBGaXJld29ya3MgOLVo0ngAAACqSURBVBiVY5BDAwxECGRlpgNBtpoKCMjLM8jnsYKASFJycnJ0tD1QRT6HromhHj8YMOcABYqEzc3d4uO9vIKCIkULgQIlYq5haao8YMBUDBQoZWIBAnFtAwsHD4kyoEA5l5SCkqa+qZ27X7hkBVCgUkhRXcvI2sk3MCpRugooUCOooWNs4+wdGpuQIlMDFKiWNbO0dXTx9AwICVGuBQqkFtQ1wEB9LhGeAwDSdzMEmZfC0wAAAABJRU5ErkJggg==
EOFILE;
$pngFolderGo = <<< EOFILE
iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAJISURBVDjLpZPLS5RhFIef93NmnMIRSynvgRF5KWhRlmWbbotwU9sWLupfCBeBEYhQm2iVq1oF0TKIILIkMgosxBaBkpFDmpo549y+772dFl5bBIG/5eGch9+5KRFhOwrYpmIAk8+OjScr29uV2soTotzXtLOZLiD6q0oBUDjY89nGAJQErU3dD+NKKZDVYpTChr9a5sdvpWUtClCWqBRxZiE/9+o68CQGgJUQr8ujn/dxugyCSpRKkaw/S33n7QQigAfxgKCCitqpp939mwCjAvEapxOIF3xpBlOYJ78wQjxZB2LAa0QsYEm19iUQv29jBihJeltCF0F0AZNbIdXaS7K6ba3hdQey6iBWBS6IbQJMQGzHHqrarm0kCh6vf2AzLxGX5eboc5ZLBe52dZBsvAGRsAUgIi7EFycQl0VcDrEZvFlGXBZshtCGNNa0cXVkjEdXIjBb1kiEiLd4s4jYLOKy9L1+DGLQ3qKtpW7XAdpqj5MLC/Q8uMi98oYtAC2icIj9jdgMYjNYrznf0YsTj/MOjzCbTXO48RR5XaJ35k2yMBCoGIBov2yLSztNPpHCpwKROKHVOPF8X5rCeIv1BuMMK1GOI02nyZsiH769DVcBYXRneuhSJ8I5FCmAsNomrbPsrWzGeocTz1x2ht0VtXxKj/Jl+v1y0dCg/vVMl4daXKg12mtCq9lf0xGcaLnA2Mw7hidfTGhL5+ygROp/v/HQQLB4tPlMzcjk8EftOTk7KHr1hP4T0NKvFp0vqyl5F18YFLse/wPLHlqRZqo3CAAAAABJRU5ErkJggg==
EOFILE;
$gifLogo = <<< EOFILE
R0lGODlhogBxAPcAAMPT4XSCjABVonGWs3x9flyi2arC2EhlfZWVlSqLxyRVfaWlpUmFuWuEmQBZpOTk5LW1tZCsxLm5ua6urtHc5jZ5ssXFxZqamsHBwbGxseDg4IWrzDpbdszMzN7e3lOLvKGhoYzH7ebp7IODg5OrvQFcplOd1t3m7djY2HOUrgJcpitcg9Th6+zt7qmpqXijyLDE1ZW10peirJHK7uLi4oiSmpy61Nvb25CQkY2NjXSFk7zU5dDQ0K29y0lpg+rs7YmJidbW1tri6dra2uHm6srKyqKqsb6+vkRri8PN1AB6whxRfYS52T1jgejq7V6Eop2dnabJ4QxJemt8ikNlgTJiiszU28rc6gBSoGWo1bnDzGKUwUptiWqaxAtepjxrklR7m7u7u7rN3qK91lNzjdPT0xpTgYOUodLS0mZ6i3uNnN3h5SRurVp6k3WOorTK3GR0gRNMeyRZhMjIyEtyk87OzgB0vlt1imSIpqO1w8nQ1s3Z5YGdtdHg6VFthYOLkgBMnRBip8fV4l1xglJ2k5vN7BllqbDBzg1gpll+nBNkqO3t7dzj6Shxr+Ho7bO/yJuwwLHG23Z+hUl1ml2Rv2uNqtre4j5oih5qqy5afXiWr4aKjTVgg9nl7TNegGSFoDpmiay7xwFYowBcpQt8wS50sc7g7HqQomV+kkNoh4+mugBQnwRYpGyJoGl2go6bpyteh2F3iQZcpb/L1d7k6gpHeaGxvaqrrHqKlwF3wGaYw+To7MrY4wBuvAJcpR9VgP///+zs7AJDeEFymoChu8DQ3evr6+bm5unp6e/z9yJbiRJPgFF+ourq6qC4zM/c5ujo6GGKqzJmkefn5+zt7aisr+3u7tDW3IicrbDN5JCUl2+Bj7a6vQBWo3+22YKGioWgtliAoN/n7tnk6zpffkVylsPIzaGjpEt4nMHX5o6wz+zs7b/Q4NLY3djc36TR7b3Hz0Vujtff55GVmWx5g3uGj42isszY4zZnj0B/tiJSeSdYgCpWe1F4l1Fwib/DxyH5BAAAAAAALAAAAACiAHEAAAj/ABcJHEiwoMGDCBMqXMiwocOHECNKnEixosWLGDNq3Mixo8ePIEOKHEmypMmTKFOqXNhC3MqXMDdauxLCVIuYOHNCPBFiRohOOoMKNdhihtEZhYYqFdqpp9GkS6PC/OHU6DupWFU2PToDaNavGG8qtFaIawhHYNNS3FEgipOERc3+UEv34S4TBUxEUWiWBcIfkbYYUvRBUF21LPDmHZfQ1NEQbws6scEGSzcHDrphAXAYbOICoLMldBKi9AmD7AxhcVBCha/WDgLN7Yz1M+gCYg+2cJJb4I8tAhyoUNG6hPFRAuTRxtpHcV60D/eUEjDKOPHhoxysYjB7+VJTzk1c/wnm0AYWUcbTlxjVrVspddS8S73ivECWhkQ+UB+enr2AD8rJV1t9BTC0Bxv7qSfKfxQI+NIP3nizQ28GOXHbbZEhtIEA6LU2nANY5NOggy9F0YsddiQgRHwIZVOfCAjlh8Uo/K0nABtvUEjiSdSkY4cSSuRCSh8JiVBfdwTxgkg3/H0oQBcZ7rhSCwnkAmQuuRCJkBAmdLnDOgapE5yHxgmACDtS4vSDj0AGOWRCJ6RzRYW6zEjccVhQQkSaOjHx45Wk+PUQERVgURxxoogSA586WWNNlW0KyVhDAHjRjYfEYcFGgIzqJAIpbQaZgDUMjRHcnSqA+EKUnea0w59XQv+HUAvq2HlnN15E0qpJLdCi40EmYpniDywa9AMlhl43ChYM7LkrSSIwIEAjLwiCZEHUWLNDFgkU4NVBROQjgHWpChBDsc+K9MGMDghw4xi7KETND+RtacilxTnAyhvpliTIKuqV0K4sW/AyUaXCFSeKLCP2OxIjigiH6nrdCMCAGNcq9Mapw6nQDRtCOGzSG6vQ6EuTxomCBSYGsHqQDSV37HEFzopckg0CYCFAN9VN3G4gLzCS0AszkilABS7bLJIQBmzwASI7V6deu6J0sYdBXRRdwmt5Zqy0ST/ssYVmrGGK3NEG3PQDA1jcuR4WG4D5dUxCbBDIagGXoHIpY0j/22S7587taQyYcCh1vuelV64Bggs1rxilWNaz4sWNgkjDjQvVgiC6OEAjufw5gAmnmQ+1TiSBHF5jufmwg27pOekiS3HGed7xKAuyYYPXsKe0QbL8CeBFZjRiByIbBvDeO0lZH1qCAKsK8UHFPRN3PGfL86if2XATJAQlUXcssMWYZw+SE/rJjNyiBlEwNs/XldDeBsqbf5EIFQjQ5PoKUcBAe1LLFCYMZj+O7KIClwodFgxAqoXIY13wQ9RmCqgRIjRCf/nqBr8aEh9BSEsUHYsNjChoEUbci1z6EsPrGsIONkisBKvYIAknQgFDgPA1qeqGYShCAfj5QgDqmOFE//bgBfR0bGFX4+EHjKgCLNhAiBERxJg8hKvyOeQHYsgfkyiGBdJBcSGRYEXCjNMNQwgtInt4QSAMl52c5YOAX2RIJPB2nTKO0CEiiEThguMAlXUDEbrAXhxLZaf0CMAQ8XKIICjhhZ1pphuyYMAY5FG/QRIEZ9X7YSnuqBBajCFyWNBZILpgAAokzZIJMYCtiHO0SrZgD9MDxCpkkQ917IE81FghKhNiquINh1n1o4U6FLEKQPgikJzcJUQiQZ3KYeEDCcHiEgFRNQAkU5kQYQfe0pOnLW3AC7JsRAwSiU2KCAERCcvUC+Q2EBHY4IKAEAAl9vCrcj5kHf+jXTcYUP8sEbBDF+BcRSNscEZ7WkQezTxON2LwAwqMoQKywMIqLPYGXRo0ItYwD7mM4wVL6QwLvnhByC6qkRdsUX2ZwUIFDEBOkmZkDG1DFXJE8QE0ubQjRODQekDUjRfQ4qYgiYRqPqaOggL1I064hzwsetSmOjUrwYhqvQgi1alSVao5qWpUWxUMYyADGdOAxiwOcYhrdBUZ0DjGMazQA7JG1avQCCtZD7GGlJw1rQ/Iaw/2WlarOsgY0HgADTTwCGkMYxjKsMI0HuABD4BDGYcdBh6QcYwHaEADT4jsMupakrMeQwMeSEIlzCCMyCJ2GSmwBImCgQzGoqAMYHAGMIBBjBT/aAAFaOgALJ4xW2Aswx23LcMjlDHbZCzDJF09Bg1uUAZb0IEY4uhtb5NBDDwwlS7BOIYHglAEC3yCGLOtLQo6cAQZSEO6w8hDEDpgATBEYLYRqARyp3HbDmAgHrKVrn6jQYK/PmC8R4BAG8ALDGeAoQ4ScAES3tvbYdiiCGGAwBKiCwxpzKKzrR2vBM4wDOkW48MUBgYM0PFXGpQBAxlYABkIXAx8YMAFCKhFMqTLDHscYQI6YMZsxfELZBjjx1qV6o+BHOQiC5nIxjjGDToQBhc0Ib8wWIYCFLCPODC4GF/oKpGD/ONmeLkZQzayVsPMZWN82RhYlUgzNMCDI7jg/wI66DAwilEFCFxgEDoGBm9p+4kMgAAU+R2AJmhAgySoIgWIJoEV0lrZQ6fgGnrgQwr4oIe8RloTJLDENCqrB0Rr4QGQQLQqLDCBC8SBwtKYAhCAkAMuENgZ4cgrDbQg6RSAY9GVfUAoEJ0ESEziC5BohyYwDVa1wgPRPZD1rlOAaUvg9QGOvgYfvoCOHqiZzWFYAAK2IWc63yIH/IDBbKMR3kS4QBvL6K0ytGCORCgjGsSIdzSU8QQ9DAEP8CaGuwdAjAEoAw/hUAa/o7EMTdwAHsqItzR+wYx4M0MOqECAMHorDBBcAAEIiHO80xsEPsBCGvzuN731gAJIDCPeyv9gBgyKwYwnyFsVoA2FNDZuCzzE4eTyXkYlbnDvfONjAMWAgTT4EBFjYFvbU5AzMCo+gnTrWc7EaAMI7kBuEX/BAv0gsH6JAYYiSGHGxah6caUhdmCIYxn/cMMAZjuAEOv5F99w+tLVoAZcgGABZ/jEJ0jQgVZIY8/S1XcRviBu2kqXuHPGRxB40I/8DqMfzJixdJPBDE3M4etzLkZvxSGHeiIkGA8owxG0HYDzzlYYFzjA2oExgG6v4AL70DwwouEG8/b2GcUIsTAgMHFgSF66hZfuAD4x4B3rFxjMGATigREBZhxWGMKoQiu4gYEwmMHt0l3GBGChebBLfvXJiIP/BTCAeXGYYfn6pYAceF/cZMi+wkmACOhFr20c9H7pCDj1bJfh+j8g3rjVUHys9wsrsAR7Ngy4oHTEsAzCsHoFxoD5VQwrsAKyVwzKIAzLUHjEQAUydnyzVQwDsAyv0ABVt4AYWHjDoAb3Fw0KYHrEIHu7R4LhdQn5xQzQpwwUJgwJOHawsHrDcAjy9wBB4GYIkAP3pwylN1swwA9OVwz74Gqz5Qzx4AKokG9NMAXaEHuzpQxpkGfOQA4B4ApyJg5xEABxFoVNYIBbGAvbBnUH0ATR8HvH5wyX4AniRoZTsA1nCAzDEABO9wxLIAmIB3SntwCcUHjKgHnO4AlTEAAr/3Z6XQhfqSCDFXZhEHEMKIABt1CE9zcMnFCDg3B/wqB/fHgGCwAFsaAAkDUMy6CFS+cDBJZ8QAAHchYBTZADSRdePtB7z/ALOIAD3KaLQEAFy9BwEfBhgLd0HfgMpuV4uUhbVEAP0vBh0uB4OoB4MJAJpucMprVnwgCLszUMOkCCH/YF7OQQmKiJFwAEasiHmJcMtQAEomh65pdiXDCN0hWHerYEmVB4y7AJQOADq8cMaZADfjCQsbCNoIAAOOAPA7kNDLkJseADTTBlS6B0wmB6HuhbBzlbBAkEg6AP+gCOfOiQ46Z6G7mP/bh/55ABpyANwOZXDIGJpFaE+iB7w/9QdbYIBKQoDAwWAYQwATWgDHLoex9IZTBYhCTZhziwlM9IDGQABU1JYMMQD9C3AhGXA0AwAvJIcXKGex8WlsWgAEupBlK5lR3Jh2oIj03AYmL5YRFABa4oDBJwBB0QBBoADRIxDUNAaut4k+GIiPXwDYC5dBSmDDLgAqnAYM7AgMqwZ8Swix+4AlCAAHNZmQoAg1CIfGoAApYJg90GC9q2lbT4gfrgg/uQmqq5D7EwlzfmmUAghuFlehFADuF2equZmqlQD73XYh3AAyjgAQ/QDHt5A3OQARcwAoWZZ72IA8ope6v3DHIwASDwC7wFj64wAijJev7gdDAACudwAUv/QAG+JwWeOZ6+VwtUwGDDcAYggAOYJ53dVgW3AAU5MALksHrOkAlUqQMXAAWpcFjK8AfW6XtxUAc3Zp+lSVsMJg30UJioBwU1wH+siAPeWQ434AEa8ADQIJMMAQ03UATIOQIc8GrjhgrOqQ+Ft2fR0AoLcAG9qQBwMAjkwJ7BSFtSB6MfCAueGaOZyXaX4A+csHoRwAVylgzDAH3QF3njRgWxyAVkwAV5Rgxc0Jv4MF4QsAA5QABOB137CAQ/6ltkQAaXYKNQlwJqNQ0+5qELgQwe0AEQgAAEUKL6tQznIKd0mn3V4JkdyHqHxWDAoAyxUHXR0AAg4H9RiASHiniL/0iKyeAMxJBfgRoASreR8LidyRABxBABkicN9cCo4cBmo7elvDhudwAEt2l28ZZfySAFgzpuJABmWzURbgqnyZmnUUgHyDmnWldgdAAB7+kJklpcOegPVOmeexh150Cp4UUFvFiUtogDpLiRzEAFgliUkpisKSCEFnALOEAAfbp/84ADeEatXGCs4QiEF4EM2AYCQLCdHokNwAoEuIp82CABpLcMzjBjySB00dWLh7h/1bAAbTCQp7AAdzCQg0CbfzdbzxANqfAHOeADy3CMk1cMEaAMqcCQVCANMCB5/coMSFADBeuReYCJx4kAhPl+Ulh/TcAM7ycOziANihqwvv/FWRbRDEKoiQgABOSgpMKQCPYFY5Lws0oqtChmcTrQBFIgDFLgCWTAgBB3CpcAff0QBhlwC3QAfYQgARNwDqkAfeRQrtz5C9AnBw3wtUUoCRUJtFKwAmQgA7cQnggwBZ7QtE4LCqeQtVoLfU+AVh6AYJ45CAqgpHQgAxlAt62ppGYQD68wARNAtX7LphBhDA8wBB2AryAABQsAAXNQBiiwXvgKBZwLARYAugCWAS6wAKzLurcwARAQuxBwBBbQAbZrAUcQBhgwBx3QXVjrAp6ZA04ajmrgAhmgu7gLAcB7cRcHBSBgvLSbvLewACBwd7cwuxiAAUcgAbpbB0PwAF7/pQFBYAEpdncTYJc8YF/KW73mi71HsL20ywMecAyU+xDBAA31tb11OQdBoKHbVQTbO7v8q6H1hbthIAEI/L4YYAFzMAdF0AGo+1q2ywNBUMG5hQHKewE48IlbaAS0C8GLVwQYIAEZALmwK8A8UAaLNwcBDAF1Wbs8kL4TjAJ5mVweUAa4+8LAeQMowAMsLAGxKwG7+5syDME38ADIkBHB0Ayf1cMzvKGVdVsyDJxQrFw3sHi2a7t1kMJBgAJeHJyXBVpenKGXdcXkRZ2feXq/GQQ3cFkeIMFzYAFyzLtoAMZinFtF8MAUPAQ30MderKHH0AxR1VrbxQNbzMY0IFhv/5y+edwBddzHPIcCQyCc02AMGsFaUdxYUIwMzUBZlqXJD3AMPtYMgQVaHtDHmqwBhJbIoaxWapVXrRzF45ulFxCfsNDGoRxWiwVaPDzGGhrKaJXJkLyhrQzLx6Cm9eJVygVaqnwM0PBVUQzJv+zKxgwNgrwRXdXJ0PDMgixkX7XNnLxVb/XN2/zMX3XOnDxkZnZmXaZkZ7wAFIixeMDNVWVmYLVp06CmsurNcRVW6dxlXoZmUzXO6CzQUaXNYfXM6nxms8on7IrDEJABblAF+IAHevBUGaGz46W9GNABKEADSYzRF5FkUhzDNHwMlizSFoHJvAzIyFC/Kt0QXrVpuRH80jGNEW9FZDe90zzd0zEREAA7
EOFILE;
$pngPlugin = <<< EOFILE
iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsSAAALEgHS3X78AAAABGdBTUEAALGOfPtRkwAAACBjSFJNAAB6JQAAgIMAAPn/AACA6QAAdTAAAOpgAAA6mAAAF2+SX8VGAAABmklEQVR42mL4//8/AyUYIIDAxK5du1BwXEb3/9D4FjBOzZ/wH10ehkF6AQIIw4B1G7b+D09o/h+X3gXG4YmteA0ACCCsLghPbPkfm9b5PzK5439Sdg9eAwACCEyANMBwaFwTGIMMAOEQIBuGA6Mb/qMbABBAEAOQnIyMo1M74Tgiqf2/b3gVhgEAAQQmQuKa/8ekdYMxyLCgmEYMHJXc9t87FNMAgACCGgBxIkgzyDaQU5FxQGQN2AUBUXX/vULKwdgjsOQ/SC9AAKEEYlB03f+oFJABdSjYP6L6P0guIqkVjt0DisEGAAQQigEgG0AhHxBVi4L9wqvBBiEHtqs/xACAAAIbEBBd/x+Eg2ObwH4FORmGfYCaQRikCUS7B5YBNReBMUgvQABBDADaAtIIwsEx9f/Dk9pQsH9kHTh8XANKMAIRIIDAhF9ELTiQQH4FaQAZCAsskPNhyRpkK7oBAAEEMSC8GsVGkEaYIlBghcU3gbGzL6YBAAEEJnzCgP6EYs/gcjCGKQI5G4Z9QiswDAAIIAZKszNAgAEAHgFgGSNMTwgAAAAASUVORK5CYII=
EOFILE;
$pngWrench = <<< EOFILE
iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAA3NCSVQICAjb4U/gAAABO1BMVEXu7u7n5+fk5OTi4uLg4ODd3d3X19fV1dXU1NTS0tLPz8+7z+/MzMy6zu65ze65zu7Kysq3zO62zO3IyMjHx8e1yOiyyO2yyOzFxcXExMSyxue0xuexxefDw8OtxeuwxOXCwsLBwcGuxOWsw+q/v7+qweqqwuqrwuq+vr6nv+qmv+m7u7ukvumkvemivOi5ubm4uLicuOebuOeat+e0tLSYtuabtuaatuaXteaZteaatN6Xs+aVs+WTsuaTsuWRsOSrq6uLreKoqKinp6elpaWLqNijo6OFpt2CpNyAo92BotyAo9+dnZ18oNqbm5t4nt57nth7ntp4nt15ndp3nd6ZmZmYmJhym956mtJzm96WlpaVlZVwmNyTk5Nvl9lultuSkpKNjY2Li4uKioqIiIiHh4eGhoZQgtVKfNFdha6iAAAAaXRSTlMA//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////914ivwAAAACXBIWXMAAAsSAAALEgHS3X78AAAAH3RFWHRTb2Z0d2FyZQBNYWNyb21lZGlhIEZpcmV3b3JrcyA4tWjSeAAAAKFJREFUGJVjYIABASc/PwYkIODDxBCNLODEzGiQgCwQxsTlzJCYmAgXiGKVdHFxYEuB8dkTOIS1tRUVocaIWiWI8IiIKKikaoD50kYWrpwmKSkpsRC+lBk3t2NEMgtMu4wpr5aeuHcAjC9vzadjYyjn7w7lK9kK6tqZK4d4wBQECenZW6pHesEdFC9mbK0W7otwsqenqmpMILIn4tIzgpG4ADUpGMOpkOiuAAAAAElFTkSuQmCC
EOFILE;
$favicon = <<< EOFILE
AAABAAEAQEAAAAEAIAAoQgAAFgAAACgAAABAAAAAgAAAAAEAIAAAAAAAAAAAABMLAAATCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJFQABWRTgAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACYVAA4mFQAeJRUAISgWACU4HwAkPCIAG0YnAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJFPAAGSWRGIk3dTEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACYVABUmFQBTJhUAhSYVAL0lFADjJRQA8igWAPUtGQD4Nh4A90EkAOxKKQDVUS0At1YwAHpaMgA6XTQACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMSgA1lGctlQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmFQAGJhUATSYVALAmFQDuJRUA/yQUAP8nFQD/LxoA/zshAP9FJgD/TSsA/1ItAP9VMAD/VzAA/1kxAP9aMgD/XDMA/100AOFdNACLXTQAIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf0cAhJlsM4cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUMAAUoFgBXJhUA0SYVAP8lFAD/JBQA/yoXAP83HwD/RScA/1EtAP9XMAD/WjIA/1syAP9bMwD/XDMA/1wzAP9cMwD/XDMA/1wzAP9cMwD/XDQA/1w0APBfNQKXaD8LJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHM/ANWcc0B6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACUVACsiEwC/JhUA/yYVAP8kFAD/KRcA/zogAP9MKgD/VzAA/1syAP9dNAD/XzUA/2I3AP9mOAD/aDoA/2s7AP9rPAD/azwA/2s7AP9qOwD/aDoA/2c5AP9mOQD/ajsA/28+APd4QwBuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFk1BhxsOQD/oHZCgwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACYVAGImFQDvJxUA/yQUAP8mFQD/Nx4A/0wqAP9YMQD/XjQA/2U4AP9uPQD/eEIA/39HAP+ESQD/h0sA/4lMAP+KTQD/ik0A/4lNAP+ISwD/hkoA/4RJAP+BSAD/fkYA/3xFAP98RQD/f0YA/4RJALuKTQAjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABbMgBEaTcA/5NoNKMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJhUAASYVAIsmFQD/JhUA/yQUAP8sGAD/RCYA/1cxAP9hNgD/bj0A/3xFAP+HSwD/jk4A/5BQAP+SUQD/k1IA/5NSAP+TUgD/k1EA/5JRAP+RUQD/kVAA/5BQAP+QUAD/j1AA/41OAP+LTQD/iUwA/4lMAP+JTAD/jE4A4o9QAD0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVTACZmQ1AP+SWxbcvLGkCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJhUAASYVAJUmFQD/JRQA/yQUAP80HQD/TywA/2I2AP9yPwD/g0gA/45OAP+SUAD/lFIA/5ZUAv+ZVwX/nFsJ/55dDf+fXg7/nl4O/51cC/+bWgj/mVcE/5ZVAf+UUgD/klEA/5FRAP+RUQD/kVEA/5BQAP+PUAD/j08A/49QAP+QUAD1kVEARAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEstBYlgNQD/hEYA/7ighEcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACYVAIcmFQD/JBQA/ycWAP9AJAD/XTQA/3VAAP+ISgD/lFMB/5paCP+eXxD/oGIU/6FjFf+iYxT/oWIT/6FiFP+hYxT/oWMU/6FiFP+hYhP/oWIT/6BhEf+fXw7/nVwK/5tYBv+XVQH/lFIA/5JRAP+RUQD/kVEA/5FRAP+RUQD/kVEA/5FRAPKRUQA9AAAAAAAAAAAAAAAAAAAAAAAAAABFJgCeWzMA/3pAAP+jcjirAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACYVAHcmFQD/JBQA/yoYAP9JKQD/azoA/4dKAP+dXg7/qW8n/7B7OP+yfj7/sX07/613Mv+obib/pGcb/6FjFP+gYRL/oGES/6FiE/+hYhP/oWIT/6FiE/+hYhP/oWIT/6BhEv+fYBD/n14N/51bCP+aWAX/l1UC/5RTAP+SUQD/kVEA/5FQAP+QUAD/kVAA4ZJSACMAAAAAAAAAAAAAAAAAAAAAOCIHr1gwAP9vPgD/iEcA/7Wbe1QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACYVADsmFQD5JBQA/ysYAP9OKwD/cj4A/5ZWB/+vdzH/uotR/72RWv+9kVn/u41U/7aFR/+ueDX/p2wi/6FjFf+fXw7/nl4N/59gEP+hYhP/oWIT/6FiE/+hYhP/oWIT/6FiE/+hYhP/oWIT/6BhEv+fYBD/n18Q/59eDv+eXQz/nVwK/5taCP+ZVwX/l1UC/5hVAv+cWgm1AAAAAAAAAAAAAAAAAAAAADMdAqFTLwD/ZDgA/4BFAP+PVRDlnotyKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACohFhEmFADVJBQA/ykXAP9MKgD/cz4A/5tcD/+3hUb/v5Rf/7+UXv+9kFn/vZFa/7yPVv+0gkP/p2sh/55dDP+ZVgT/l1UC/5pWA/+dXAr/oGES/6FiE/+hYhP/oWIT/6FiEv+hYRL/oWES/6FhEv+gYRL/oGER/6BhEf+gYRL/oWMV/6NnGv+lah//pmsg/6VqHv+laB3/pmoe/6Z0NnQAAAAAAAAAAAAAAAAuHAWKTysA/100AP9zQAD/hkkA/4dGANeYeVMlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC0oIRIoHAy4JRQA/yYVAP9FJgD/bzwA/5laC/+4h0n/xZ1t/8upfv/KqHv/wpll/72QWf+7jlX/q3Mt/5dVAv+SUQD/kVEA/5FRAP+SUQD/mVYD/6BgEP+hYhP/oWIT/6FiE/+hYxX/omQW/6NlGP+kZhr/pGcb/6RnG/+kZxv/o2cb/6RoHP+mayH/qnEq/613M/+vejb/rnk2/655Nf+weznhsIBFGAAAAAAAAAAAMRwAbEopAP9bMwD/ZjkA/35GAP+GSQD/iEwD64VjOU8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACogEzUoGQfSJBMA/yQUAP8+IwD/ZjgA/5BRBP+1gkH/xJ1r/9Cxif/TtI//0bON4MijdJa9kVuNt4dKy51dD/+QTgD/kVEA/5FRAP+RUQD/kVEA/5RSAP+fXw//o2YZ/6VqH/+pbyf/rHUw/697Of+yfz//tIJE/7WDRf+1g0X/s4JD/7J/Pv+wezn/r3k3/7B8Ov+zgEH/tYVH/7WFSP+1hEf/toRF/7KJVpIAAAAAAAAAADgeAE5HKAD/WjIA/181AP91QQD/g0kA/4NIAP92QgH/ZEATvmVRN1BnXVEIAAAAAAAAAAAAAAAAAAAAAAAAAAAqJSECKSMbOigbCqclEwD7JBMA/yYVAP89IgD/XjQA/4RIAP+qcCf/v5Nd/8upfv/StI//0LGJr9KzjQwAAAAAAAAAAAAAAACOTwJ7ekMA/3xFAP+GSgD/jk8A/5BQAP+UUwH/pWgc/612Mf+yfz7/t4ZK/7qMUv+7jlb/vJBY/72QWf+9kFn/vZBZ/7yPV/+6jVT/uIlO/7aGSf+1hUj/t4hM/7qMUv+7jVT/uoxT/7qMUv+6jFLstpBgGgAAAAA+JQYkSCgA+FgxAP9cNAD/bj0A/4NJAP+GSwD/fEQA/2Q2AP9bMgD/XTgK3lY5FatINh+IMCYZeyUcEYQmGQuiJRcG1CQUAPwkEwD/JhUA/zEbAP9HKAD/WjIA/3lCAP+aWgr/uIdL/7+UX//MqoD/0rSO7dKzjiEAAAAAAAAAAAAAAAAAAAAAAAAAAF00AL1eNAD/bDwA/4VJAP+QTwD/mFgH/7B6N/+4iU7/u45W/7yPV/+8kFn/vZJb/76SXP+9klv/vJBY/72QWf+9kVr/vZBZ/7uOVf+5i1D/uIhN/7mKUP+8j1b/vZBZ/72QWf+8kFj/vI9W/7iSYmoAAAAARyoGA0sqAdNXMAD/XDMA/2c6AP+CSAD/i00A/4hLAP94QwD/YzcA/1wyAP9aMQD/UywA/0gnAP87IAD/MhsA/y8ZAP8xGwD/OSAA/0goAP9WMAD/XzUA/3NAAP+OTgD/p20k/72QWf+9klv/xp9w/8yrgLMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABULgB2WTIA/100AP97RQD/kE4A/6NmG/+6jFL/vJBZ/72SW//BmGX/xqBw/8ikdv/IpHb/xp9w/8CXY/+8kFn/vZBZ/72RWv+8j1f/uotR/7eHS/+3iE3/vI5W/72RWv+9kVr/vZFa/72RWf+6k2PGAAAAAAAAAABOLwmOWDAA/1wzAP9iNwD/fkYA/41OAP+OTwD/iUwA/3pEAP9nOQD/XTQA/1szAP9aMgD/VzEA/1QvAP9TLgD/VS8A/1kyAP9eNAD/aToA/35GAP+NTgD/l1YE/7F9O/+9kVr/vZFa/72RWv+/lF+3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOyEAe1ItAP9cNAD/e0QA/5VTAv+xfTz/vZFb/8KZZv/Kp3v/z6+H/9GyjP/Rsoz/0LCI/8yqfv/Gn27/vZFX/7uMUv+8j1b/u45V/7iJT/+0gkT/sn9A/7iKT/+9kVr/vJBZ/7yQWP+8kFj/vZBX9LuSXiAAAAAAUDUUMFgxAfxcMwD/XzUA/3hCAP+MTgD/kFAA/5BQAP+MTgD/g0kA/3VBAP9pOgD/YjcA/2A1AP9gNQD/YjcA/2c5AP9wPgD/fUUA/4pNAP+RUQD/kVAA/6BiFP+1g0X/vI9W/72QWf+9kFn/vI9W9reFRzIAAAAAAAAAAAAAAAAAAAAAIxQACikXAM9MKgD/YDUA/4NHAP+jZhr/vI9W/8afb//QsIn/0rSO/9Gzjf/RsYr/0rOL/9K2kujRuJm4z7ibmMmylo3EpoCWwZxus76UYeC1g0T/rXUv/6dsIv+veTX/u49W/72RWf++k1v/v5Re/72RWf+2k2hUAAAAAAAAAABZNAa+XTMA/100AP9yPwD/ik0A/5FRAP+RUQD/kVEA/5BQAP+NTwD/iEwA/4JIAP9/RwD/f0cA/4RJAP+JTAD/j08A/5FRAP+SUQD/klEA/5dVAv+nbCL/tIFD/7iJTv+5ilD/toVI/6tzLP+XVgXLcj0AJgAAAAAAAAAAMRsADyITAJ4sGAD/US0A/248AP+UVAX/tIJD/8Webf/Rsov/0bKL/86tg//Nq4D/zbKQxdDBrlnZzb8PAAAAAAAAAAAAAAAAAAAAAAAAAADNvakJuJlyT6JtK7iWUgD+mlkJ/7OAQf+9kFn/v5Rf/8Wfb//EnWv/wZhjfgAAAAAAAAAAVzkTUl00AP9cMwD/bDwA/4dLAP+RUQD/kVEA/5FRAP+RUQD/kVEA/5FRAP+RUAD/kVAA/5JRAP+SUQD/k1EA/5RSAP+VVAH/mVcE/5xbCf+gYBD/p20k/696N/+yfz//sX07/6dsIv+VUwL/jU4A/3A+APNbMwC9Uy4Atj4iAOc1HQD/RicA/2I2AP+ISgD/rXYw/8KaZv/PsIj/z7CJ/8qmev/LqX7u0LeYXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApHtIRJBQAeCeXxH/uYlO/76SXP/GoHL/y6d7/8aogqIAAAAAAAAAAAAAAABbNgetXDMA/2c5AP+BSAD/j1AA/5FRAP+UUgD/mlcE/5taCf+bWgn/m1sJ/5tbCf+cWwr/nFwL/51dDP+fXg7/n2AQ/6FhEv+hYhP/oWIU/6RpHv+pcCn/q3Mt/6huJv+dXQz/klAA/45PAP92QgD/XTQA/1oyAP9XMAD/VjAA/2M3AP+DRwD/qG0k/7+VX//NrYT/0LGK/8mlef/Lq4La0L2lLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAChhWEall0axadsIv+8kFf/w5tp/86sgv/Mr4m3AAAAAAAAAAAAAAAAXTMBOVwzAPtkOAD/e0QA/4xOAP+RUQD/klEA/5tYBf+gYBD/oWIT/6JjFP+iYxT/omMU/6JjFP+iYxT/oWMU/6FiFP+hYhP/oWIT/6FiE/+iZRf/pWgd/6VpHv+hYxX/mFUD/5FRAP+QUAD/hUoA/28+AP9kOAD/ZjkA/3E+AP+ISgD/p2wi/76SW//MqoD/0bKM/8uofP/Gn2/1zrOPMgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALGjkBWbYBjSs38+/7+VYP/Mq4D/0bGLyQAAAAAAAAAAAAAAAAAAAABbOQ+BZjgA/3hDAP+JTAD/kVAA/5FRAP+WVAH/n14N/6FiE/+hYhT/oWIT/6FiE/+hYhP/oWIT/6FiE/+hYhP/oWIT/6FiE/+hYhP/oWIU/6JkFv+hYxX/nl0M/5ZUAP+RUQD/kVEA/45PAP+KTAD/hkkA/4pKAP+XVgb/rXUv/7+UXv/MqoH/0bKM/8upfv/HonP/xqBwcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwa6WOKZrIfi8j1f/yaV3/9C1kswAAAAAAAAAAAAAAAAAAAAAajkAB287ALh5QwD/hksA/49PAP+RUQD/k1EA/51bCf+iYxb/omUY/6JkF/+hYxX/oWIT/6FiE/+hYhP/oWIT/6FiE/+hYhP/oWIT/6FiE/+hYhP/oGER/55dC/+YVQH/klAA/5FQAP+SUAD/lVMB/5xdDf+obyf/t4VI/8OaZ//OrIP/0bKL/8upff/HonP/xqBwpQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACyjmCLtIA//8Wfb//Rs47EAAAAAAAAAAAAAAAAAAAAAAAAAABuTCIXe0gI1oZKAP+OTwD/kVEA/5FRAP+ZVwT/o2UX/6ZqIP+maiH/pGgd/6NmGf+hZBb/oWIT/6FhEv+hYRL/oWES/6FhEv+hYRL/oGES/6BgEf+fYBD/oGAQ/6BhEv+jZxv/qnAp/7F9PP+5ik7/v5Re/8eic//QsYr/0LGK/8uoff/HonT/xqBws8agcAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvaeMKq54NfjCmWb/0LGKuQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHpPGR+KSwDZjk4A/5FQAP+RUQD/lFIA/6FiE/+obyf/q3Mu/6t0Lv+qciz/qG8n/6ZrIv+laB3/o2YZ/6JkF/+iZBb/o2QX/6RnG/+mayH/qnIr/696OP+1g0X/uotR/7yPV/++klz/w5tq/82rgf/StI7/z7CI/8qoff/Ho3X/x6FyvMagcREAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC0iVO6vpFZ/86thJoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhFIUGoxSCsGRUAD/kVEA/5FRAP+dXAv/qG4m/695Nv+yfz//s4FC/7SCQ/+zgUL/s4BB/7J/P/+yfz//sn9A/7OBQv+1hEf/t4hM/7qMUv+7jlb/vJBY/72RWv/Bl2P/yKR2/9Cxif/StI7/z6+H/8upfv/IpHf/x6JzqMeicw0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAr45jeryOVP/Kpnt2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIWSANklAAl5FRAP6RUAD/mFYE/6VpHv+ueTb/tIJE/7eITP+5ilD/uoxT/7uOVf+7jlb/vI9X/7yQWP+9kFr/vZFa/72RWv+9kFn/vZFb/8CWYv/HoXL/zayD/9Kzjf/Rs43/z6+H/8yqf//Kp3r9yKR3jMejdQUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALWKU1m8jlb/w51rRwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACRUQBAkVAA3ZdUAf+jZRj/rXUx/7SCQ/+4ik//u41U/7yPWP+9kFn/vZFa/72RWv+9kVr/vZBZ/7yQWP+9klv/wZhk/8agcf/Mqn//0LGK/9K0jv/Ss43/z7CI/82sgv/MqX7Qyqd7PgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC0ootKu41T9L2RWhcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI9SBg6YVwV2o2YY4Kx1L/+zgUH/uIlO/7uOVf+8kFj/vZFa/72RWv+9kFn/vJBY/72RWv/AlmL/xZ5u/8mmev/OrYT/0LKL/9K0jv/Rs43/0LGK/86uhuHNrIJqzKl+CQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArYVRYLyOVr4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKVoHBCtdzNus4FD1LiJTv+7jlX/vJBZ/72RWv+9kFn/vJBY/7yQWf/BmGT/xqBw/8qne//OrYT/0LGK/9K0jv/StI710bONwdCximfPr4YOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALGETXy8jVJfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALSDRAW5ilAvu45WZr2QWae9kVrQvZBZ3byQV/C+k133xJxq9cijde7MqX/gz66Gx9Gyi4vStI5Y0rSOHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwg0yLsIdUFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvZFaAb2QWQi8kFccvpJcJcScaiHIo3UYzKl+CgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACqdjYErns7IgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////z/////wH//+P////wAB//5////4AAB//n///+AAAB/+f///wAAAD/x///+AAAAD/H///gAAAAH8P//8AAAAAPw///wAAAAAfD//+AAAAAA8H//wAAAAADwP/+AAAAAAHAf/wAAAAAAMA/+AAAAAAAwAfAAHAAAABAAAAA+AAAAEAAAAH4AAAAYAAAAfgAAAAgAAAA8AAAADAAAABgAD4AMAAAAAAB/8A4AAAAAAP/4DgAAAAAB//wPAAAAAAP//g8AAAAAB///D4AAAAAH//8PwAAAAA///4/gAAAAH///j/AAAAA///+P/AAAAP///4/+AAAB////n/+AAAf///+f/+AAP////5///gP/////P///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8=
EOFILE;

if (isset($_GET['img']))
{
    switch ($_GET['img'])
    {
        case 'pngFolder' :
        header("Content-type: image/png");
        echo base64_decode($pngFolder);
        exit();

        case 'pngFolderGo' :
        header("Content-type: image/png");
        echo base64_decode($pngFolderGo);
        exit();

        case 'gifLogo' :
        header("Content-type: image/gif");
        echo base64_decode($gifLogo);
        exit();

        case 'pngPlugin' :
        header("Content-type: image/png");
        echo base64_decode($pngPlugin);
        exit();

        case 'pngWrench' :
        header("Content-type: image/png");
        echo base64_decode($pngWrench);
        exit();

        case 'favicon' :
        header("Content-type: image/x-icon");
        echo base64_decode($favicon);
        exit();
    }
}

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

$link = "./";
if($_GET['dir']){$link = $_GET['dir'];}

// Security
$JError = "";
if(substr($link,0,2) != "./" OR @ereg("\.\.\/", $link)){
  $link = "./";
  $JError = "<script>alert('Error! Permission denied for requested path.');</script>";
}

?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title>liMil Tools - <? echo $link; ?></title>

    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <style type="text/css">
* {
    margin: 0;
    padding: 0;
}

html {
    background: #ddd;
}
body {
    margin: 1em 10%;
    padding: 1em 3em;
    font: 80%/1.4 tahoma, arial, helvetica, lucida sans, sans-serif;
    border: 1px solid #999;
    background: #eee;
    position: relative;
}
#head {
    margin-bottom: 1.8em;
    margin-top: 1.8em;
    padding-bottom: 0em;
    border-bottom: 1px solid #999;
    letter-spacing: -500em;
    text-indent: -500em;
    height: 125px;
    background: url(?img=gifLogo) 0 0 no-repeat;
}
.utility {
    position: absolute;
    right: 4em;
    top: 145px;
    font-size: 0.85em;
}
.utility li {
    display: inline;
}

h2 {
    margin: 0.8em 0 0 0;
}

ul {
    list-style: none;
    margin: 0;
    padding: 0;
}
#head ul li, dl ul li, #foot li {
    list-style: none;
    display: inline;
    margin: 0;
    padding: 0 0.2em;
}
ul.aliases, ul.projects, ul.tools {
    list-style: none;
    line-height: 24px;
}
ul.aliases a, ul.projects a, ul.tools a {
    padding-left: 22px;
    background: url(?img=pngFolder) 0 100% no-repeat;
}
ul.projects {

    margin-top: 1.8em;
    border-top: 1px solid #999;
    padding-top: 1em;

}

li.tools a {
    padding-left: 25px;
    background: url(?img=pngPlugin) 0 100% no-repeat;
}
li.phptools a {
    padding-left: 25px;
    background: url(?img=pngWrench) 0 100% no-repeat;
}
ul.tools a {
    background: url(?img=pngWrench) 0 100% no-repeat;
}
ul.aliases a {
    background: url(?img=pngFolderGo) 0 100% no-repeat;
}
dl {
    margin: 0;
    padding: 0;
}
dt {
    font-weight: bold;
    text-align: right;
    width: 11em;
    clear: both;
}
dd {
    margin: -1.35em 0 0 12em;
    padding-bottom: 0.4em;
    overflow: auto;
}
dd ul li {
    float: left;
    display: block;
    width: 16.5%;
    margin: 0;
    padding: 0 0 0 20px;
    background: url(index.php?img=pngPlugin) 2px 50% no-repeat;
    line-height: 1.6;
}
a {
    color: #024378;
    font-weight: bold;
    text-decoration: none;
}
a:hover {
    color: #04569A;
    text-decoration: underline;
}
#foot {
    text-align: center;
    margin-top: 1.8em;
    border-top: 1px solid #999;
    padding-top: 1em;
    font-size: 0.85em;
}

</style>
<?
echo $JError;
?>
<link rel="shortcut icon" href="index.php?img=favicon" type="image/ico" />
</head>

<body>
<?

$links = array_filter(explode("/",$link));

echo "<b>";
$lin_ = "";
$lina = "";

foreach($links as $lin){
  $lina = $lin_;
  if($lin == "."){
      $lin_ = "./";
      echo "<a href='?dir=".$lin_."'>Root</a>";

  }else{
      $lin_ = $lin_.$lin."/";
      echo " <font color='#888'>►</font> <a href='?dir=".$lin_."'>".$lin."</a>";

  }

}


echo "</b>";
?>

    <ul class="projects">

<?PHP







$ofile = opendir($link);
echo "<div style='text-align: left'>";
while (($file = readdir($ofile)) !== false) {
    if($file == "." OR $file == ".htaccess" OR (basename(__FILE__) == "$file" AND $link == "./")){ continue; }

      if(filetype($link.$file) == "dir"){
              if($file == ".."){
                if($link != "./"){
                    echo "<li><a href='?dir=".$lina."'>".$file."</a></li>";
                }
              }else{
                  echo "<li><a href='?dir=".$link.$file."/'>".$file."</a></li>";
              }

      }else{
               if(substr($file,-3) == "php"){$class = "phptools";}else{$class = "tools";}
               $FSize = filesize ($link.$file)/1024;
               if($FSize > 1024){
                    $FSize =  round($FSize/1024,2)."M";

               }else{
                    $FSize =  round($FSize,2)."K";
               }
              echo "<li class='".$class."'><a href='".$link.$file."'>".$file."</a> (".$FSize.")</li>";
      }

if($file == "index.html" OR $file == "index.php"){header("Location: ".$link.$file);die();} 

}
echo "</div>";
?>
</ul>



    <ul id="foot">
        <li><a target="_blank" href="http://www.limil.ir">liMil Arc.</a></li> -
        <li><a target="_blank" href="http://www.Google.com">Google</a></li>
    </ul>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-TK0P6JS218"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-TK0P6JS218');
</script>
</body>
</html>

<?


function FileFormt($fdata){
  if (0 > $fdata){$fdata = $fdata * -1; }
    if($fdata < 1024){
      return $fdata." B";
    }elseif($fdata < (1024*1024)){
       return round($fdata/1024)." KB";
    }elseif($fdata < (1024*1024*1024)){
       return round($fdata/(1024*1024),1)." MB";
    }elseif($fdata < (1024*1024*1024*1024)){
       return round($fdata/(1024*1024*1024),2)." GB";
    }else{
       return $fdata;
    }
}

?>